name: app_it
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.11.0
  auto_size_text: ^3.0.0
  simple_gradient_text: ^1.2.4
  animated_text_kit: ^4.1.0
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  url_launcher: ^6.0.20
  flutter_native_splash: ^2.2.16
  lottie: ^2.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/image/logo.png
    - assets/image/bg1.png
    - assets/image/bg2.png

    - assets/image/Home.png
    - assets/image/Contact.png
    - assets/image/Profile.png
    - assets/image/Back.png
    - assets/image/TT.png
    - assets/image/shapeImage3.png
    - assets/image/c3.png
    - assets/image/shapeImage5.png
    - assets/image/shapeImage4.png
    - assets/image/shapeImage.png
    - assets/image/Yt.png
    - assets/image/Ig.png
    - assets/image/folder.webp
    - assets/image/ShapeCloud.png
    - assets/image/Wa.webp
    - assets/image/logo2.webp
    - assets/image/folder.webp

  fonts:
    - family: Valken
      fonts:
        - asset: assets/font/Valken.ttf
    - family: MVS
      fonts:
        - asset: assets/font/MVS.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/font/Poppins.ttf
    - family: Robotto
      fonts:
        - asset: assets/font/Robotto.ttf
