name: app_it
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  simple_gradient_text: ^1.2.4
  animated_text_kit: ^4.1.0
  google_nav_bar: ^5.0.6
  google_mobile_ads: ^3.0.0
  firebase_core: ^2.15.0
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  url_launcher: ^6.0.20
  flutter_native_splash: ^2.2.16
  lottie: ^2.1.0





flutter:
  uses-material-design: true
  assets:
    - assets/data.json
    - assets/image/logo.png
    - assets/image/icon-update/Stack.png
    - assets/image/icon-update/Mag.png
    - assets/image/icon-update/Mag1.png
    - assets/image/icon-update/Mag2.png
    - assets/image/bg1.png
    - assets/image/bg2.png
    - assets/image/logo3.png
    - assets/image/Home.png
    - assets/image/Contact.png
    - assets/image/Profile.png
    - assets/image/Back.png
    - assets/image/TT.png
    - assets/image/shapeImage3.png
    - assets/image/c3.png
    - assets/image/shapeImage5.png
    - assets/image/shapeImage4.png
    - assets/image/shapeImage.png
    - assets/image/Yt.png
    - assets/image/Ig.png
    - assets/image/folder.webp
    - assets/image/ShapeCloud.png
    - assets/image/Wa.webp
    - assets/image/logo2.webp
    - assets/image/folder.webp
    - assets/image/bg3.png
    - assets/image/image-medsos/tiktok.png
    - assets/image/image-medsos/instagram.png
    - assets/image/image-medsos/yotube.png

  fonts:
    - family: Valken
      fonts:
        - asset: assets/font/Valken.ttf
    - family: MVS
      fonts:
        - asset: assets/font/Roboto-Medium.ttf
    - family: Rmedium
      fonts:
        - asset: assets/font/MVS.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/font/Poppins.ttf
    - family: Robotto
      fonts:
        - asset: assets/font/Robotto.ttf
