// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpdyDgEI9rkgeTD1b3JTNh1RLlDSE_3OQ',
    appId: '1:620933646315:web:699458c9873c45548cfbae',
    messagingSenderId: '620933646315',
    projectId: 'bigdata-aplikasiitc',
    authDomain: 'bigdata-aplikasiitc.firebaseapp.com',
    databaseURL: 'https://bigdata-aplikasiitc-default-rtdb.firebaseio.com',
    storageBucket: 'bigdata-aplikasiitc.appspot.com',
    measurementId: 'G-07N6N98L4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRmpncHMRhUzLzd4vytV4YHYxwOOgB3Ps',
    appId: '1:620933646315:android:52b77d974ec0d4548cfbae',
    messagingSenderId: '620933646315',
    projectId: 'bigdata-aplikasiitc',
    databaseURL: 'https://bigdata-aplikasiitc-default-rtdb.firebaseio.com',
    storageBucket: 'bigdata-aplikasiitc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCs4S22NDT2vrLYY4zo6YG50FWeaIAvIo',
    appId: '1:620933646315:ios:06102882c1c2e0888cfbae',
    messagingSenderId: '620933646315',
    projectId: 'bigdata-aplikasiitc',
    databaseURL: 'https://bigdata-aplikasiitc-default-rtdb.firebaseio.com',
    storageBucket: 'bigdata-aplikasiitc.appspot.com',
    iosClientId: '620933646315-oii08603190ci4btnf9pf78776pda5qk.apps.googleusercontent.com',
    iosBundleId: 'com.example.appIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCs4S22NDT2vrLYY4zo6YG50FWeaIAvIo',
    appId: '1:620933646315:ios:06102882c1c2e0888cfbae',
    messagingSenderId: '620933646315',
    projectId: 'bigdata-aplikasiitc',
    databaseURL: 'https://bigdata-aplikasiitc-default-rtdb.firebaseio.com',
    storageBucket: 'bigdata-aplikasiitc.appspot.com',
    iosClientId: '620933646315-oii08603190ci4btnf9pf78776pda5qk.apps.googleusercontent.com',
    iosBundleId: 'com.example.appIt',
  );
}
